name: jgitver demo
on:
  push:
    branches:
      - '**'
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      # The checkout action in previous step overwrites annonated tag
      # with lightweight tags breaking ``git describe``
      # See https://github.com/actions/checkout/issues/882
      # and https://github.com/actions/checkout/issues/290
      # The following step is a workaround to restore the latest tag
      # to it's original state.
      - name: Restore (annonated) tag
        run: git fetch --force origin ${GITHUB_REF}:${GITHUB_REF}
        if: ${{ github.ref_type == 'tag' }}

      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          architecture: x64
          cache: 'maven'
      - name: Building application
        run: |
          ./mvnw -V -B clean validate
