name: jgitver demo
on:
  push:
    branches:
      - '**'
    tags:
      - v*.*.*

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Java and Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: x64
          cache: 'maven'
      - name: Building application
        run: |
          ./mvnw -V -B clean validate